import type {
  OpportunityPage,
  OpportunityRead,
  OpportunityScoreRead,
} from "@/features/opportunities/types";

export const mockOpportunityScore: OpportunityScoreRead = {
  id: "score-101",
  profile_version_id: "ver-001",
  score_total: 82.5,
  confidence_score: 0.85,
  confidence_level: "HIGH",
  components: {
    price: 90,
    reliability: 85,
    liquidity: 75,
    mechanical_risk: 80,
    mileage: 70,
    age: 75,
    history: 85,
    condition: 90,
    listing_age: 65,
  },
  score_breakdown: {
    price: {
      sub_score: 90,
      weight: 0.3,
      weighted_points: 27.0,
      reason: "Precio 22% por debajo de estimación de mercado",
    },
    reliability: {
      sub_score: 85,
      weight: 0.15,
      weighted_points: 12.8,
      reason: "Modelo en WHITELIST con 0 fallos críticos reportados",
    },
    liquidity: {
      sub_score: 75,
      weight: 0.1,
      weighted_points: 7.5,
      reason: "Alta demanda histórica para SEAT Ibiza en el segmento",
    },
    mechanical_risk: {
      sub_score: 80,
      weight: 0.1,
      weighted_points: 8.0,
      reason: "Motor 1.9 TDI con distribución demostrable",
    },
    mileage: {
      sub_score: 70,
      weight: 0.1,
      weighted_points: 7.0,
      reason: "145.000 km, por debajo de la media del año (180.000 km)",
    },
    age: {
      sub_score: 75,
      weight: 0.05,
      weighted_points: 3.8,
      reason: "14 años de antigüedad",
    },
    history: {
      sub_score: 85,
      weight: 0.05,
      weighted_points: 4.3,
      reason: "Bajada de precio de 200€ detectada",
    },
    condition: {
      sub_score: 90,
      weight: 0.05,
      weighted_points: 4.5,
      reason: "ITV en vigor y fotos de calidad",
    },
    listing_age: {
      sub_score: 65,
      weight: 0.1,
      weighted_points: 6.5,
      reason: "20 días en venta, oportunidad activa",
    },
  },
  calculated_at: "2026-09-09T08:00:00Z",
};

export const mockOpportunity: OpportunityRead = {
  id: "opp-001",
  vehicle_id: "veh-001",
  listing_id: "list-001",
  score_id: "score-101",
  status: "IDENTIFIED",
  currency: "EUR",
  asking_price: "1700.00",
  estimated_market_price: "2400.00",
  estimated_fast_sale_price: "2100.00",
  target_purchase_price: "1350.00",
  estimated_transfer_cost: "55.70",
  estimated_tax: "68.00",
  estimated_repair_min: "50.00",
  estimated_repair_max: "150.00",
  estimated_preparation_cost: "200.00",
  estimated_total_cost_min: "2073.70",
  estimated_total_cost_max: "2173.70",
  estimated_margin_min: "-73.70",
  estimated_margin_max: "26.30",
  estimated_roi_min: "-3.50",
  estimated_roi_max: "1.25",
  confidence_level: "HIGH",
  seller_pressure_level: "MEDIUM",
  seller_pressure_reasons: [
    "20 días en mercado",
    "Bajada de precio acumulada de 200 € (-10.5%)",
  ],
  notes: "Contactar antes del fin de semana",
  created_at: "2026-09-09T08:00:00Z",
  updated_at: "2026-09-09T08:00:00Z",
  score: mockOpportunityScore,
  title: "SEAT Ibiza 1.9 TDI",
  brand: "SEAT",
  model: "Ibiza",
  generation: "IV",
  trim: "Stella",
  engine_code: "AGR",
  fuel_type: "DIESEL",
  transmission: "MANUAL",
  year: 2010,
  mileage_km: 145000,
  city: "Valencia",
  province: "Valencia",
  external_url: "https://ejemplo.com/seat-ibiza",
  source_name: "Mock Portal",
};

export const mockOpportunityPage: OpportunityPage = {
  items: [mockOpportunity],
  page: 1,
  page_size: 15,
  total: 1,
  has_more: false,
};
